name: AVD Playground

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - run: |
          ls $ANDROID_HOME
          ls $ANDROID_SDK_ROOT
          ls $ANDROID_NDK
      - name: create AVD and generate snapshot for caching  
        uses: FLGMwt/android-emulator-runner@debug-sdk-install
        # env:
        #   ANDROID_HOME: ${{ env.ANDROID_HOME }}
          # ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          # ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_ROOT }}
          # ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          # ANDROID_NDK: ${{ env.ANDROID_NDK }}
        with:
          api-level: 29
          # ndk: 27.3.13750724
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
